#!/bin/bash

git clone git@github.com:Presence-Web-Services/growinggreen-site.git

cd ./growinggreen-site

upload="$1"
title="$2"
numPhotos="$3"
captions="$4"
types="$5"

hugo new photos/upload${upload}.md

sed -i "s|description: \"\"|description: \"${title}\"|g" content/photos/upload${upload}.md

for (( i=0; i<$numPhotos; i++ )); do
  j=$(($i + 1))
  caption=$(echo $captions | awk -F',' "{print \$$j}")
  type=$(echo $types | awk -F',' "{print \$$j}")
  echo -e "{{< photos/gallery-image upload=\"$upload\" photo=\"$i\" type=\"$type\" caption=\"$caption\" >}}\n" >> content/photos/upload${upload}.md
  if [[ $i -eq 0 ]]; then
    echo -e "<!--more-->\n" >> content/photos/upload${upload}.md
  fi
done

./build

git add .
git commit -m "Added photogroup upload${upload}"
git push
